// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: advisor.sql

package db

import (
	"context"
)

const getEQAdvisorByID = `-- name: GetEQAdvisorByID :one
SELECT id, code, description FROM hamonix_business.eq_advisors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEQAdvisorByID(ctx context.Context, id string) (HamonixBusinessEqAdvisor, error) {
	row := q.db.QueryRow(ctx, getEQAdvisorByID, id)
	var i HamonixBusinessEqAdvisor
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}
