// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: asset.sql

package db

import (
	"context"
)

const getListAssetsByPortfolioId = `-- name: GetListAssetsByPortfolioId :many
SELECT id, portfolio_id, ticker_id, price, allocation FROM hamonix_business.assets
WHERE portfolio_id = $1
ORDER BY id
`

func (q *Queries) GetListAssetsByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessAsset, error) {
	rows, err := q.db.Query(ctx, getListAssetsByPortfolioId, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HamonixBusinessAsset{}
	for rows.Next() {
		var i HamonixBusinessAsset
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TickerID,
			&i.Price,
			&i.Allocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
