// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type HarmonixBusinessAsset struct {
	ID                 int64   `json:"id"`
	PortfolioProfileID string  `json:"portfolio_profile_id"`
	TickerName         string  `json:"ticker_name"`
	Price              float64 `json:"price"`
	Allocation         float64 `json:"allocation"`
}

type HarmonixBusinessHrnProfileAccount struct {
	ID        int64     `json:"id"`
	ProfileID string    `json:"profile_id"`
	AccountID string    `json:"account_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

type HarmonixBusinessPortfolioProfile struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Privacy        string    `json:"privacy"`
	AuthorID       string    `json:"author_id"`
	Advisors       []string  `json:"advisors"`
	Branches       []string  `json:"branches"`
	Organizations  []string  `json:"organizations"`
	Accounts       []string  `json:"accounts"`
	ExpectedReturn float64   `json:"expected_return"`
	IsNewBuyPoint  bool      `json:"is_new_buy_point"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
