// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: portfolio_organization.sql

package db

import (
	"context"
)

const getEQOrganizationByID = `-- name: GetEQOrganizationByID :one
SELECT id, backoffice_id, code, description FROM hamonix_business.eq_organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEQOrganizationByID(ctx context.Context, id string) (HamonixBusinessEqOrganization, error) {
	row := q.db.QueryRow(ctx, getEQOrganizationByID, id)
	var i HamonixBusinessEqOrganization
	err := row.Scan(
		&i.ID,
		&i.BackofficeID,
		&i.Code,
		&i.Description,
	)
	return i, err
}
