// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: portfolio_branch.sql

package db

import (
	"context"
)

const getEQBranchByID = `-- name: GetEQBranchByID :one
SELECT id, code, description FROM hamonix_business.eq_branchs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEQBranchByID(ctx context.Context, id string) (HamonixBusinessEqBranch, error) {
	row := q.db.QueryRow(ctx, getEQBranchByID, id)
	var i HamonixBusinessEqBranch
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}
