// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountProfilesInCategory(ctx context.Context, categoryID pgtype.Text) (int64, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (HamonixBusinessAsset, error)
	CreatePAdvisor(ctx context.Context, arg CreatePAdvisorParams) (HamonixBusinessPAdvisor, error)
	CreatePBranch(ctx context.Context, arg CreatePBranchParams) (HamonixBusinessPBranch, error)
	CreatePCategory(ctx context.Context, arg CreatePCategoryParams) (HamonixBusinessPCategory, error)
	CreatePOrganization(ctx context.Context, arg CreatePOrganizationParams) (HamonixBusinessPOrganization, error)
	CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (HamonixBusinessPortfolio, error)
	CreatePortfolioCategory(ctx context.Context, arg CreatePortfolioCategoryParams) (HamonixBusinessPortfolioCategory, error)
	CreateUCategory(ctx context.Context, arg CreateUCategoryParams) (HamonixBusinessUCategory, error)
	DeleteAsset(ctx context.Context, arg DeleteAssetParams) error
	DeletePAdvisor(ctx context.Context, arg DeletePAdvisorParams) error
	DeletePBranch(ctx context.Context, arg DeletePBranchParams) error
	DeletePCategory(ctx context.Context, arg DeletePCategoryParams) error
	DeletePOrganization(ctx context.Context, arg DeletePOrganizationParams) error
	DeletePortfolio(ctx context.Context, id string) error
	DeletePortfolioCategory(ctx context.Context, id string) error
	GetAssetsByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessAsset, error)
	GetCategoryInfo(ctx context.Context, id string) (HamonixBusinessPortfolioCategory, error)
	GetEQAdvisorByID(ctx context.Context, id string) (HamonixBusinessEqAdvisor, error)
	GetEQBranchByID(ctx context.Context, id string) (HamonixBusinessEqBranch, error)
	GetEQOrganizationByID(ctx context.Context, id string) (HamonixBusinessEqOrganization, error)
	GetPAdvisorByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessPAdvisor, error)
	GetPBranchByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessPBranch, error)
	GetPCategoryByCategoryId(ctx context.Context, categoryID pgtype.Text) ([]HamonixBusinessPCategory, error)
	GetPCategoryByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessPCategory, error)
	GetPOrganizationByPortfolioId(ctx context.Context, portfolioID string) ([]HamonixBusinessPOrganization, error)
	GetPortfolioCategoryById(ctx context.Context, id string) (HamonixBusinessPortfolioCategory, error)
	GetProfilesByPortfolioId(ctx context.Context, id string) (HamonixBusinessPortfolio, error)
	GetUCategoryByUserId(ctx context.Context, userID string) ([]HamonixBusinessUCategory, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (HamonixBusinessAsset, error)
	UpdatePAdvisor(ctx context.Context, arg UpdatePAdvisorParams) (HamonixBusinessPAdvisor, error)
	UpdatePBranch(ctx context.Context, arg UpdatePBranchParams) (HamonixBusinessPBranch, error)
	UpdatePCategory(ctx context.Context, arg UpdatePCategoryParams) (HamonixBusinessPCategory, error)
	UpdatePOrganization(ctx context.Context, arg UpdatePOrganizationParams) (HamonixBusinessPOrganization, error)
	UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (HamonixBusinessPortfolio, error)
	UpdatePortfolioCategory(ctx context.Context, arg UpdatePortfolioCategoryParams) (HamonixBusinessPortfolioCategory, error)
}

var _ Querier = (*Queries)(nil)
