// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPortfolio = `-- name: CreateUserPortfolio :one
INSERT INTO hamonix_business.u_portfolio (
  user_id,
  portfolio_id
) VALUES (
  $1, $2
) RETURNING id, user_id, portfolio_id
`

type CreateUserPortfolioParams struct {
	UserID      string      `json:"user_id"`
	PortfolioID pgtype.Text `json:"portfolio_id"`
}

func (q *Queries) CreateUserPortfolio(ctx context.Context, arg CreateUserPortfolioParams) (HamonixBusinessUPortfolio, error) {
	row := q.db.QueryRow(ctx, createUserPortfolio, arg.UserID, arg.PortfolioID)
	var i HamonixBusinessUPortfolio
	err := row.Scan(&i.ID, &i.UserID, &i.PortfolioID)
	return i, err
}
